# Generated by Django 3.2.9 on 2021-11-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('reference_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('concept', models.CharField(max_length=255)),
                ('director_notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=100)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='play.play')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='play.play')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('sketches', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('reference_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='play.play')),
            ],
        ),
    ]
