# Generated by Django 3.2.9 on 2021-11-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='play_id',
            new_name='play',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='play_id',
            new_name='play',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='play_id',
            new_name='play',
        ),
    ]
