# Generated by Django 3.2.9 on 2021-11-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_auto_20211118_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='reference_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
